# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('user_owner', models.CharField(default='anonim', max_length=50)),
                ('image_class', models.CharField(choices=[('car', 'class of cars'), ('face', 'class of faces'), ('tree', 'class of trees')], max_length=20)),
                ('image', models.ImageField(upload_to='')),
                ('date_adding', models.DateField(auto_now_add=True)),
                ('image_format', models.CharField(default=None, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ImagesDatasets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=50)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('image_class', models.CharField(choices=[('car', 'class of cars'), ('face', 'class of faces'), ('tree', 'class of trees')], default='face', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(error_messages={}, max_length=40, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('residence_place', models.CharField(max_length=80, null=True)),
                ('status', models.CharField(default='new_user', max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='images',
            name='image_dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_processing.ImagesDatasets'),
        ),
        migrations.AddField(
            model_name='images',
            name='image_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_processing.Users'),
        ),
    ]
